version: '2'
services:
  mysql:
    image: "mysql:5.6"
    volumes:
      - ${EXTERNAL_DATA_DIR}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_OPENMRS_USER}
      MYSQL_PASSWORD: ${MYSQL_OPENMRS_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_OPENMRS_DATABASE}
  couchdb:
    image: "klaemo/couchdb:1.6.1"
    ports:
      - "5984:5984"
    volumes:
      - ${EXTERNAL_DATA_DIR}/couchdb:/usr/local/var/lib/couchdb
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
  couchdb-lucene:
    image: "klaemo/couchdb-lucene"
    ports:
      - "5985:5985"
    volumes:
      - ${EXTERNAL_DATA_DIR}/couchdb-lucene:/opt/couchdb-lucene/indexes
    entrypoint: /bin/bash -c 'chown -R couchdb:couchdb /opt/couchdb-lucene; sleep 1; gosu couchdb /opt/couchdb-lucene/bin/run'
  activemq:
    image: "rmohr/activemq:5.11.1"
    ports:
      - "8161:8161"
  postgres:
    image: postgres:10.2
    restart: always
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: ${OPENSRP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${OPENSRP_POSTGRES_PASSWORD}
      POSTGRES_DB: ${OPENSRP_POSTGRES_DATABASE}
    volumes: 
      - postgres-tablespaces:${OPENSRP_TABLESPACE_ROOT}
  redis:
      image: redis:4.0.9
      command: 
          --requirepass ${REDIS_PASSWORD}
      ports:
        - "6379:6379" 
      volumes:
        - redis-data:/data
  migrations:
      build:
        context: .
        dockerfile: ./Migration_Dockerfile
      depends_on:
        - postgres
      volumes:
        - postgres-tablespaces:${OPENSRP_TABLESPACE_ROOT}
        - ./migrations:/migrate
        - ./migrate.sh:/migrate.sh
      environment:
        DB_PORT_5432_TCP_ADDR: postgres
        DB_PORT_5432_TCP_PORT: 5432
        DB_ENV_POSTGRES_SCHEMA: ${OPENSRP_POSTGRES_DATABASE}
        DB_ENV_POSTGRES_USER: ${OPENSRP_POSTGRES_USER}
        DB_ENV_POSTGRES_PASSWORD: ${OPENSRP_POSTGRES_PASSWORD}
        OPENSRP_TABLESPACE_ROOT: ${OPENSRP_TABLESPACE_ROOT}
  opensrp-composed:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_MOTECH_DATABASE: ${MYSQL_MOTECH_DATABASE}
      MYSQL_OPENMRS_DATABASE: ${MYSQL_OPENMRS_DATABASE}
      MYSQL_OPENMRS_USER: ${MYSQL_OPENMRS_USER}
      MYSQL_OPENMRS_PASSWORD: ${MYSQL_OPENMRS_PASSWORD}
    depends_on:
      - mysql
      - couchdb
      - couchdb-lucene
      - activemq
      - postgres
      - migrations
      - redis
    ports:
      - "9090:8080"
    volumes:
       - ./webapps:/webapps
volumes:
  redis-data:
  postgres-tablespaces: